// NodeSettingsView — faithful web replica of views/NodeSettingsView.qml.
//
// Three LogosFrame cards, one per concern:
//   1. Node (config)      — user + deployment config paths (field + Browse + copy),
//      the generated/built-in notes, "Config changed. Start the node to use it."
//      notice, Update config (only when stale) and Start a new node. Every control
//      is disabled while the node is running (canChange).
//   2. Back up your keys  — "Done" badge when backed up, keystore path (or "No
//      keystore found yet…"), Download keystore.yaml. SUCCESS is a shell-level toast
//      (see note below); FAILURE is the inline, closable + copyable notice.
//   3. Reset the database — red border, instructions + database path (or "No database
//      found yet…"). Guidance only, no button.
//
// The config state, paths and keystore live on the desktop host, not the node HTTP
// API, so the web replica models them as props/state (defaults = a fresh, never-run
// node → the absent states). Actions that the host would perform (keystore backup,
// config upgrade) are injected as an async `api` so the parent/shell — or a test —
// wires the real behaviour.

import { useCallback, useRef, useState } from "react";

import { Badge, Button, Card, CopyButton, HashRow, TextField, Toast } from "../ds";
import { useCapabilities } from "../deploy/capabilities";
import { registerParity } from "../test/parity";
import { NodeOffNotice } from "../shell/NodeOffNotice";
import type { NodeViewProps } from "./types";
import { ConfigUpgradeDialog, type ConfigUpgradeState } from "./ConfigUpgradeDialog";
import "./NodeSettingsView.css";

// Settings parity ids (view "Settings").
registerParity([
  "settings-config-card",
  "settings-user-config-field",
  "settings-user-config-browse",
  "settings-user-config-copy",
  "settings-deployment-field",
  "settings-deployment-browse",
  "settings-config-changed-notice",
  "settings-update-config",
  "settings-start-new-node",
  "settings-config-canchange",
  "settings-keys-card",
  "settings-keys-download",
  "settings-keys-backup-error",
  "settings-keystore-absent",
  "settings-reset-db-card",
  "settings-db-absent",
]);

/** The host-provided node-settings model (QML root properties). */
export interface NodeSettingsModel {
  userConfig: string;
  deploymentConfig: string;
  /** Config was generated by this app (shows "Generated by this app."). */
  useGeneratedConfig: boolean;
  /** The chooser is reachable only while the node is stopped. */
  canChange: boolean;
  /** The node refused this config as older than this release. */
  configStale: boolean;
  nodeRunning: boolean;
  /** A path was repointed and the node has not been started since. */
  configChangedSinceStart: boolean;
  /** Where the node keeps db/state/logs. Empty = no config / never run. */
  nodeDataDir: string;
  /** The keystore path, or empty when there is none for this config yet. */
  nodeKeystorePath: string;
  keysBackedUp: boolean;
}

const DEFAULT_MODEL: NodeSettingsModel = {
  userConfig: "",
  deploymentConfig: "",
  useGeneratedConfig: false,
  canChange: true,
  configStale: false,
  nodeRunning: false,
  configChangedSinceStart: false,
  nodeDataDir: "",
  nodeKeystorePath: "",
  keysBackedUp: false,
};

/** The result of a successful config upgrade (feeds the dialog's upgraded face). */
export interface ConfigUpgradeResult {
  dropped: string[];
  backupPath: string;
  reportPath: string;
}

/** Host actions injected into the view (defaults are safe no-ops for the replica). */
export interface NodeSettingsApi {
  /** Write a copy of the keystore to the chosen destination. Rejects on failure. */
  backupKeystore: (destinationPath: string) => Promise<void>;
  /** Rebuild the config against this release. Rejects → the dialog's error notice. */
  upgradeConfig: () => Promise<ConfigUpgradeResult>;
  /** Start the node after a successful upgrade (upgraded-face "Start node"). */
  startNode: () => Promise<void> | void;
  /** Open setup for a second node ("Start a new node"). */
  startNewNode: () => void;
  /** Start fresh with a new wallet (no-keystore face). */
  startFresh: () => void;
}

export interface NodeSettingsViewProps extends NodeViewProps {
  /** Override any of the host model fields (the rest fall back to a never-run node). */
  initial?: Partial<NodeSettingsModel>;
  /** Inject the host actions (tests pass mocks). */
  api?: Partial<NodeSettingsApi>;
  /** Called when a keystore backup SUCCEEDS — the real shell raises its own toast here. */
  onBackupSuccess?: (destinationPath: string) => void;
}

export function NodeSettingsView({
  nodeOffReason,
  nodeOffSeverity,
  initial,
  api,
  onBackupSuccess,
}: NodeSettingsViewProps) {
  const caps = useCapabilities();
  const [model, setModel] = useState<NodeSettingsModel>({ ...DEFAULT_MODEL, ...initial });
  const [backupError, setBackupError] = useState("");
  // Shell-level success toast. The inventory is explicit: backup SUCCESS is a shell
  // toast, not a Settings/Keys element — so it carries no `settings-*` parity id. We
  // render it here (and call onBackupSuccess) only so the standalone replica is whole.
  const [backupToast, setBackupToast] = useState<string | null>(null);

  // Config-upgrade dialog state (driven by the Update config button / upgrade run).
  const [dialogState, setDialogState] = useState<ConfigUpgradeState>("hidden");
  const [dialogBusy, setDialogBusy] = useState(false);
  const [dialogError, setDialogError] = useState("");
  const [upgradeResult, setUpgradeResult] = useState<ConfigUpgradeResult | null>(null);

  const userBrowseRef = useRef<HTMLInputElement>(null);
  const deployBrowseRef = useRef<HTMLInputElement>(null);

  const hasKeystore = model.nodeKeystorePath.length > 0;

  const setUserConfig = useCallback((path: string) => {
    setModel((m) => ({ ...m, userConfig: path, configChangedSinceStart: true }));
  }, []);
  const setDeploymentConfig = useCallback((path: string) => {
    setModel((m) => ({ ...m, deploymentConfig: path, configChangedSinceStart: true }));
  }, []);

  // ---- Keystore backup: success → shell toast, failure → inline notice. ----
  const runBackup = useCallback(async () => {
    const dest = `${model.nodeKeystorePath.replace(/[^/]*$/, "") || ""}keystore.yaml`;
    setBackupError("");
    try {
      await (api?.backupKeystore ?? (async () => {}))(dest);
      setModel((m) => ({ ...m, keysBackedUp: true }));
      setBackupToast(`Keystore saved — ${dest}`);
      onBackupSuccess?.(dest);
    } catch (err) {
      setBackupError(err instanceof Error ? err.message : String(err));
    }
  }, [api, model.nodeKeystorePath, onBackupSuccess]);

  // ---- Config upgrade dialog flow. ----
  const openUpgradeDialog = useCallback(() => {
    setDialogError("");
    setUpgradeResult(null);
    setDialogState("stale");
  }, []);

  const runUpgrade = useCallback(async () => {
    setDialogBusy(true);
    setDialogError("");
    try {
      const result = await (api?.upgradeConfig ??
        (async () => ({ dropped: [], backupPath: "", reportPath: "" })))();
      setUpgradeResult(result);
      setDialogState("upgraded");
    } catch (err) {
      setDialogError(err instanceof Error ? err.message : String(err));
    } finally {
      setDialogBusy(false);
    }
  }, [api]);

  const startNodeFromDialog = useCallback(async () => {
    await api?.startNode?.();
    setDialogState("hidden");
    setModel((m) => ({ ...m, configStale: false, configChangedSinceStart: false }));
  }, [api]);

  const dismissDialog = useCallback(() => setDialogState("hidden"), []);

  const disabled = !model.canChange;

  return (
    <section className="view-settings" data-testid="view-node-settings">
      <NodeOffNotice reason={nodeOffReason} severity={nodeOffSeverity} />

      {!caps.fileSystem ? (
        /* Web build: config, keystore, and database are native filesystem concerns
           with no HTTP endpoint — managed by the node's host, not this UI. */
        <Card className="settings-card" data-testid="settings-host-managed">
          <div className="settings-card__head">
            <h3 className="settings-card__title">Managed by the host</h3>
          </div>
          <p className="settings-prose">
            This node runs inside its package container. Its configuration, keystore,
            and database live with the node and are managed from your DAppNode — open
            this package&rsquo;s <strong>Config</strong>, <strong>Backup</strong>, and{" "}
            <strong>File Manager</strong> tabs to change settings, back up your keys, or
            reset the database. Everything that the node exposes over its API — status,
            mining, rewards, the explorer, and the wallet — is in the tabs above.
          </p>
        </Card>
      ) : (
      <>
      {/* ---- 1. Node config card ---- */}
      <Card
        className="settings-card"
        data-testid="settings-config-card"
        data-can-change={model.canChange}
      >
        <div className="settings-card__head">
          <h3 className="settings-card__title">Node</h3>
          <button
            type="button"
            className="settings-info-button"
            aria-label="Node config info"
            data-testid="settings-config-info"
          >
            i
          </button>
        </div>

        <div className="settings-field-head">
          <span className="settings-field-label">User Config</span>
          {model.userConfig.length > 0 && (
            <CopyButton
              value={model.userConfig}
              title="Copy user config path"
              className="settings-user-config-copy"
            />
          )}
        </div>
        <div className="settings-field-row">
          <TextField
            data-testid="settings-user-config-field"
            className="settings-field-input"
            placeholder="No file selected"
            defaultValue={model.userConfig}
            disabled={disabled}
            onBlur={(e) => setUserConfig(e.target.value.trim())}
          />
          <Button
            data-testid="settings-user-config-browse"
            disabled={disabled}
            onClick={() => userBrowseRef.current?.click()}
          >
            Browse
          </Button>
          <input
            ref={userBrowseRef}
            type="file"
            className="settings-file-input"
            data-testid="settings-user-config-file"
            onChange={(e) => {
              const f = e.target.files?.[0];
              if (f) setUserConfig(f.name);
            }}
          />
        </div>
        {model.useGeneratedConfig && (
          <p className="settings-note">Generated by this app.</p>
        )}

        <div className="settings-field-head settings-field-head--spaced">
          <span className="settings-field-label">Deployment Config</span>
          {model.deploymentConfig.length > 0 && (
            <CopyButton
              value={model.deploymentConfig}
              title="Copy deployment config path"
            />
          )}
        </div>
        <div className="settings-field-row">
          <TextField
            data-testid="settings-deployment-field"
            className="settings-field-input"
            placeholder="Built-in default"
            defaultValue={model.deploymentConfig}
            disabled={disabled}
            onBlur={(e) => setDeploymentConfig(e.target.value.trim())}
          />
          <Button
            data-testid="settings-deployment-browse"
            disabled={disabled}
            onClick={() => deployBrowseRef.current?.click()}
          >
            Browse
          </Button>
          <input
            ref={deployBrowseRef}
            type="file"
            className="settings-file-input"
            data-testid="settings-deployment-file"
            onChange={(e) => {
              const f = e.target.files?.[0];
              if (f) setDeploymentConfig(f.name);
            }}
          />
        </div>
        {model.deploymentConfig.length === 0 && (
          <p className="settings-note">Using the deployment built into this build.</p>
        )}

        {model.configChangedSinceStart && !model.nodeRunning && (
          <Toast
            variant="info"
            className="settings-config-changed"
            message={
              <span data-testid="settings-config-changed-notice">
                Config changed. Start the node to use it.
              </span>
            }
          />
        )}

        <div className="settings-card__actions">
          {model.configStale && (
            <Button
              data-testid="settings-update-config"
              variant="primary"
              disabled={disabled}
              onClick={openUpgradeDialog}
            >
              Update config
            </Button>
          )}
          <Button
            data-testid="settings-start-new-node"
            disabled={disabled}
            onClick={() => api?.startNewNode?.()}
          >
            Start a new node
          </Button>
        </div>
      </Card>

      {/* ---- 2. Back up your keys card ---- */}
      <Card className="settings-card" data-testid="settings-keys-card">
        <div className="settings-card__head">
          <h3 className="settings-card__title">Back up your keys</h3>
          {model.keysBackedUp && (
            <Badge
              color="var(--success)"
              data-testid="settings-keys-done-badge"
            >
              Done
            </Badge>
          )}
        </div>

        <p className="settings-prose">
          Your keystore holds the keys to your accounts. It is the one file nothing else
          can replace — lose it and the rewards those accounts hold are gone with it. Save
          a copy somewhere safe, away from this machine, and you can recover the accounts
          even if everything here is lost.
        </p>

        {hasKeystore ? (
          <HashRow label="Keystore" labelWidth={72} value={model.nodeKeystorePath} />
        ) : (
          <p className="settings-note" data-testid="settings-keystore-absent">
            No keystore found yet — it appears once a config is set and the node has run at
            least once.
          </p>
        )}

        <div className="settings-card__actions">
          <Button
            data-testid="settings-keys-download"
            variant="primary"
            disabled={!hasKeystore}
            onClick={runBackup}
          >
            Download keystore.yaml
          </Button>
        </div>

        {backupError.length > 0 && (
          <Toast
            variant="error"
            className="settings-backup-error"
            onDismiss={() => setBackupError("")}
            message={
              <span data-testid="settings-keys-backup-error">
                <strong>Backup failed</strong> — {backupError}
                <CopyButton value={backupError} title="Copy error" />
              </span>
            }
          />
        )}
      </Card>

      {/* ---- 3. Reset the database card (destructive, red border, no button) ---- */}
      <Card
        className="settings-card settings-card--danger"
        data-testid="settings-reset-db-card"
      >
        <div className="settings-card__head">
          <h3 className="settings-card__title">Reset the database</h3>
        </div>
        <p className="settings-prose">
          If the node is stuck or will not start, its database may be at fault. Stop the
          node, delete the folder below, then start it again — it will re-sync the chain
          from its peers. Your keys and config files are untouched.
        </p>
        {model.nodeDataDir.length > 0 ? (
          <HashRow label="Database" labelWidth={72} value={model.nodeDataDir} />
        ) : (
          <p className="settings-note" data-testid="settings-db-absent">
            No database found yet — it appears once a config is set and the node has run at
            least once.
          </p>
        )}
      </Card>

      {/* Shell-level backup-success toast (not a Settings parity element). */}
      {backupToast && (
        <div className="settings-shell-toast">
          <Toast
            variant="success"
            onDismiss={() => setBackupToast(null)}
            message={<span data-testid="keystore-backup-toast">{backupToast}</span>}
          />
        </div>
      )}

      {/* Config-upgrade dialog — opened by Update config, driven through the upgrade run. */}
      <ConfigUpgradeDialog
        configState={dialogState}
        hasKeystore={hasKeystore}
        busy={dialogBusy}
        upgradeError={dialogError}
        configDropped={upgradeResult?.dropped ?? []}
        configBackupPath={upgradeResult?.backupPath ?? ""}
        mergeConfigReportPath={upgradeResult?.reportPath ?? ""}
        onUpgrade={runUpgrade}
        onStartNode={startNodeFromDialog}
        onStartFresh={() => {
          api?.startFresh?.();
          setDialogState("hidden");
        }}
        onDismiss={dismissDialog}
      />
      </>
      )}
    </section>
  );
}
